services:
  api:
    build:
      context: .
      labels:
        - "project=sisal_websubmit"
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - .env
    volumes:
      - sisal_sessions:/app/sessions
    restart: unless-stopped

volumes:
  sisal_sessions: