services:
  api:
    image: sisal_websubmit:v${APP_VERSION:-latest}
    container_name: sisal_websubmit-v${APP_VERSION:-latest}
    build:
      context: .
      args:
        - APP_VERSION=${APP_VERSION:-latest}
      labels:
        - "project=sisal_websubmit"
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - .env
    volumes:
      - sisal_sessions:/app/sessions
    restart: unless-stopped

volumes:
  sisal_sessions:

networks:
  default:
    name: sisal_network