services:
  api:
    build:
      target: development
    volumes:
      - ./src:/app/src
      - ./web:/app/web
      - ./tests:/app/tests
      - ./.coveragerc:/app/.coveragerc
    env_file:
      - .env.debug