import asyncio
import json
import os

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse, StreamingResponse

from src.services.api_utils import (
    AUTOQC_SCRIPT_PATH,
    get_session_paths,
    parse_qc_log_to_json,
)

router = APIRouter()


# ==========================================
# AutoQC Validation
# ==========================================
@router.post("/api/validate/{session_id}")
async def validate_file(session_id: str, request: Request):
    paths = get_session_paths(session_id)
    if not os.path.exists(paths["base"]):
        raise HTTPException(status_code=404, detail="Session not found or expired.")

    # Search for the uploaded file in input folder.
    files = os.listdir(paths["input"])
    if not files:
        raise HTTPException(status_code=400, detail="No file found in session.")
    filename = files[0]

    # Set up subprocess environment variables.
    env = os.environ.copy()
    env["SISAL_INPUT_DIR"] = os.path.abspath(paths["input"])
    env["SISAL_OUTPUT_DIR"] = os.path.abspath(paths["output"])

    # Run AutoQC script
    async def generate_response():
        async with request.app.state.script_semaphore:
            # Starting subprocess asyncronously
            process = await asyncio.create_subprocess_exec(
                "python",
                AUTOQC_SCRIPT_PATH,
                filename,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                env=env,
            )

            # Continously reading standard output
            while True:
                line = await process.stdout.readline()
                if not line:
                    break

                line_str = line.decode("utf-8").strip()
                if line_str:
                    try:
                        msg = json.loads(line_str)
                        if msg.get("priority") == "Status message":
                            yield (
                                json.dumps(
                                    {
                                        "type": "progress",
                                        "percentage": msg.get("percentage"),
                                        "section": msg.get("section"),
                                        "message": msg.get("description"),
                                    }
                                )
                                + "\n"
                            )
                    except json.JSONDecodeError:
                        pass

            await process.wait()

            # Process the structured QC log generated by AutoQC.
            log_path = os.path.join(
                paths["output"], "QC_log_" + os.path.splitext(filename)[0] + ".txt"
            )
            raw_log = ""

            if os.path.exists(log_path):

                def _read_log():
                    with open(log_path, "r", encoding="utf-8") as f:
                        return f.read()

                raw_log = await asyncio.to_thread(_read_log)

            report = parse_qc_log_to_json(raw_log)

            if (
                process.returncode != 0
                or report["total_fatal"] > 0
                or report["total_errors"] > 0
            ):
                yield (
                    json.dumps(
                        {
                            "type": "complete",
                            "status": "error",
                            "message": "Quality check failed: Error or Fatal messages were found.",
                            "report": report,
                        }
                    )
                    + "\n"
                )
            else:
                yield (
                    json.dumps(
                        {"type": "complete", "status": "success", "report": report}
                    )
                    + "\n"
                )

    # Using StreamingResponse with NDJSON format
    return StreamingResponse(generate_response(), media_type="application/x-ndjson")


# ==========================================
# Serve Generated Map Image
# ==========================================


@router.get("/api/map/{session_id}")
async def get_map(session_id: str):
    paths = get_session_paths(session_id)
    if not os.path.exists(paths["output"]):
        raise HTTPException(status_code=404, detail="Session not found.")

    # Search for the generated png map
    for file in os.listdir(paths["output"]):
        if file.startswith("map_") and file.endswith(".png"):
            return FileResponse(os.path.join(paths["output"], file))

    raise HTTPException(status_code=404, detail="Map not found.")
