import os
import subprocess
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from src.services.api_utils import AUTOQC_SCRIPT_PATH, get_session_paths, parse_qc_log_to_json

router = APIRouter()

# ==========================================
# AutoQC Validation
# ==========================================
@router.post("/api/validate/{session_id}")
async def validate_file(session_id: str):
    paths = get_session_paths(session_id)
    if not os.path.exists(paths["base"]):
        raise HTTPException(status_code=404, detail="Session not found or expired.")
        
    # Search for the uploaded file in input folder.
    files = os.listdir(paths["input"])
    if not files:
        raise HTTPException(status_code=400, detail="No file found in session.")
    filename = files[0]
    
    # Set up subprocess environment variables.
    env = os.environ.copy()
    env["SISAL_INPUT_DIR"] = os.path.abspath(paths["input"])
    env["SISAL_OUTPUT_DIR"] = os.path.abspath(paths["output"])
    
    # Run AutoQC script.
    try:
        result = subprocess.run(
            ["python", AUTOQC_SCRIPT_PATH, filename],
            capture_output=True,
            text=True,
            env=env
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to execute validation script: {str(e)}")
    
    # Process the structured QC log generated by AutoQC.
    log_path = os.path.join(paths["output"], "QC_log_" + os.path.splitext(filename)[0] + ".txt")
    raw_log = ""
    if os.path.exists(log_path):
        with open(log_path, "r", encoding="utf-8") as f:
            raw_log = f.read()

    report = parse_qc_log_to_json(raw_log)
    
    if result.returncode != 0 or report["total_fatal"] > 0:
        if not report["warnings"]:
            report["warnings"].append({
                "priority": "Fatal",
                "description": "A fatal error occurred while running AutoQC, but no structured log entry was produced.",
                "script_location": "main.py",
                "workbook_location": ""
            })
            report["total_fatal"] = 1
        return {
            "status": "fatal_error",
            "message": "A fatal error occurred during workbook quality check.",
            "report": report
        }
        
    return {"status": "success", "report": report}

# ==========================================
# Serve Generated Map Image
# ==========================================
@router.get("/api/map/{session_id}")
async def get_map(session_id: str):
    paths = get_session_paths(session_id)
    if not os.path.exists(paths["output"]):
        raise HTTPException(status_code=404, detail="Session not found.")
        
    # Search for the generated png map  
    for file in os.listdir(paths["output"]):
        if file.startswith("map_") and file.endswith(".png"):
            return FileResponse(os.path.join(paths["output"], file))
            
    raise HTTPException(status_code=404, detail="Map not found.")